### ISSUE TITLE
[Bug]: test failures

### ISSUE THREAD

**Issue by laysakura** [laysakura/beam#3]
## How to reproduce

```console
RUST_BACKTRACE=1 cargo test -- --skip target/debug
```

```
running 10 tests
test tests::primitives_test::tests::ensure_assert_fails_on_empty ... ignored
test tests::coders_test::tests::test_general_object_coder ... ok
test tests::primitives_test::tests::run_impulse_expansion ... ok
test tests::worker_test::tests::test_operator_construction ... ok
test tests::primitives_test::tests::run_direct_runner ... ok
test tests::coders_test::tests::test_standard_coders ... ok
test tests::primitives_test::tests::run_gbk ... FAILED
test tests::primitives_test::tests::ensure_assert_fails - should panic ... ok
test tests::primitives_test::tests::run_map ... FAILED
test tests::primitives_test::tests::run_flatten ... FAILED


---- tests::primitives_test::tests::run_gbk stdout ----
thread 'tests::primitives_test::tests::run_gbk' panicked at 'called `Option::unwrap()` on a `None` value', src/internals/serialize.rs:108:57
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/panicking.rs:64:14
   2: core::panicking::panic
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/panicking.rs:114:5
   3: core::option::Option<T>::unwrap
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/option.rs:823:21
   4: <apache_beam::internals::serialize::TypedKeyExtractor<V> as apache_beam::internals::serialize::KeyExtractor>::extract
             at ./src/internals/serialize.rs:108:24
   5: <apache_beam::worker::operators::GroupByKeyWithinBundleOperator as apache_beam::worker::operators::OperatorI>::process
             at ./src/worker/operators.rs:503:28
   6: <apache_beam::worker::operators::Operator as apache_beam::worker::operators::OperatorI>::process
             at ./src/worker/operators.rs:134:17
   7: apache_beam::worker::operators::Receiver::receive
             at ./src/worker/operators.rs:237:13
   8: <apache_beam::worker::operators::ParDoOperator as apache_beam::worker::operators::OperatorI>::process
             at ./src/worker/operators.rs:581:17
   9: <apache_beam::worker::operators::Operator as apache_beam::worker::operators::OperatorI>::process
             at ./src/worker/operators.rs:137:17
  10: apache_beam::worker::operators::Receiver::receive
             at ./src/worker/operators.rs:237:13
  11: <apache_beam::worker::operators::ParDoOperator as apache_beam::worker::operators::OperatorI>::process
             at ./src/worker/operators.rs:581:17
  12: <apache_beam::worker::operators::Operator as apache_beam::worker::operators::OperatorI>::process
             at ./src/worker/operators.rs:137:17
  13: apache_beam::worker::operators::Receiver::receive
             at ./src/worker/operators.rs:237:13
  14: <apache_beam::worker::operators::ImpulsePerBundleOperator as apache_beam::worker::operators::OperatorI>::start_bundle
             at ./src/worker/operators.rs:450:13
  15: <apache_beam::worker::operators::Operator as apache_beam::worker::operators::OperatorI>::start_bundle
             at ./src/worker/operators.rs:114:46
  16: apache_beam::worker::sdk_worker::BundleProcessor::process::{{closure}}
             at ./src/worker/sdk_worker.rs:378:13
  17: <apache_beam::runners::direct_runner::DirectRunner as apache_beam::runners::runner::RunnerI>::run_pipeline::{{closure}}
             at ./src/runners/direct_runner.rs:84:51
  18: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/future/future.rs:125:9
  19: apache_beam::runners::runner::RunnerI::run_async::{{closure}}
             at ./src/runners/runner.rs:64:41
  20: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/future/future.rs:125:9
  21: apache_beam::runners::runner::RunnerI::run::{{closure}}
             at ./src/runners/runner.rs:48:33
  22: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/future/future.rs:125:9
  23: apache_beam::tests::primitives_test::tests::run_gbk::{{closure}}
             at ./src/tests/primitives_test.rs:94:13
  24: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/future/future.rs:125:9
  25: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/future/future.rs:125:9
  26: tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}::{{closure}}::{{closure}}
             at /Users/sho.nakatani/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/scheduler/current_thread.rs:525:48
  27: tokio::coop::with_budget::{{closure}}
             at /Users/sho.nakatani/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/coop.rs:102:9
  28: std::thread::local::LocalKey<T>::try_with
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/thread/local.rs:446:16
  29: std::thread::local::LocalKey<T>::with
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/thread/local.rs:422:9

...
```

**Comment by dahlbaek** [comment]
Following the stack trace, the issue appears to be incorrectly specified typing related to `TypedKeyExtractor`. The empty option occurs at a call to `downcast_ref`

https://github.com/laysakura/beam/blob/4bfdd2642ba5b88396190a06aee1fe0e22086d99/sdks/rust/src/internals/serialize.rs#L108

It seems the type of `V` is expected to be inferred by the compiler here

https://github.com/laysakura/beam/blob/4bfdd2642ba5b88396190a06aee1fe0e22086d99/sdks/rust/src/tests/primitives_test.rs#L88

I'll be happy to look into this.

**Comment by laysakura** [comment]
@dahlbaek I assigned this issue to you (or you may assign it by yourself next time).

**Comment by dahlbaek** [comment]
The immediate issue was downcasting to tuple in a few places where the actual type was `KV`. On top of that, incorrect use of `Mutex` in

https://github.com/laysakura/beam/blob/4bfdd2642ba5b88396190a06aee1fe0e22086d99/sdks/rust/src/internals/serialize.rs#L15-L16

caused tests to fail spuriously.

**Comment by laysakura** [comment]
Closed via https://github.com/laysakura/beam/pull/7
